# Required to run your project under the correct environment.
language: php
# Versions of PHP you want your project run with.
php:
 - 7.0
 - 7.1
 - 7.2
 - hhvm
# Commands to be run before your environment runs.
before_script:
 - composer self-update

install:
- COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-dist --no-interaction

# Commands you want to run that will verify your build.
script: vendor/bin/phpunit